// apps/user/src/app/layout.tsx
import type { Viewport, Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LiffBoot from "./LiffBoot";
import StripeBoot from "./stripe/StripeBoot";
import RedeemConfirmWatcher from "@/components/RedeemConfirmWatcher";
// import "leaflet/dist/leaflet.css";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ja">
      {/* ▼▼ 追加：Stripe を含む外部ドメインへの事前接続（DNS解決/SSLハンドシェイク短縮） ▼▼ */}
      <head>
        {/* 基本 Stripe */}
        <link rel="dns-prefetch" href="https://js.stripe.com" />
        <link rel="preconnect" href="https://js.stripe.com" crossOrigin="" />

        {/* CDN 経由のアセット */}
        <link rel="dns-prefetch" href="https://m.stripe.com" />
        <link rel="preconnect" href="https://m.stripe.com" crossOrigin="" />
        <link rel="dns-prefetch" href="https://q.stripe.com" />
        <link rel="preconnect" href="https://q.stripe.com" crossOrigin="" />
        <link rel="dns-prefetch" href="https://r.stripe.com" />
        <link rel="preconnect" href="https://r.stripe.com" crossOrigin="" />
        <link rel="dns-prefetch" href="https://api.stripe.com" />
        <link rel="preconnect" href="https://api.stripe.com" crossOrigin="" />
        <link rel="dns-prefetch" href="https://stripecdn.com" />
        <link rel="dns-prefetch" href="https://*.stripecdn.com" />
        <link rel="preconnect" href="https://*.stripecdn.com" crossOrigin="" />

        {/* 埋め込みで iframe が使われる場合の保険（必要なければ残してOK） */}
        <meta httpEquiv="x-dns-prefetch-control" content="on" />
      </head>
      {/* ▲▲ 追加ここまで ▲▲ */}

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* LIFF 起動（LINE アプリ内/外の双方を考慮） */}
        <LiffBoot />

        {/* Stripe 周りの初期化：Elements/StripeAppLoader はこの子で行う想定 */}
        <StripeBoot />

        {/* 受け取り確定の依頼を自動検知してボトムシート表示 */}
        <RedeemConfirmWatcher />

        {children}
      </body>
    </html>
  );
}
